import NavBar from './components/organisms/NavBar';
import Provider from './components/organisms/Provider';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        <Provider>
          <NavBar />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
